### PR TITLE
fix(chaos): use correct json template

### LINKED ISSUE #117: NPE in NotifyHandler
It seems that the failing chaos runs causes some problems in the notify handler

```java
java.lang.NullPointerException at io.zeebe.clustertestbench.handler.NotifyEngineersHandler.composeMessage(NotifyEngineersHandler.java:65) at io.zeebe.clustertestbench.handler.NotifyEngineersHandler.handle(NotifyEngineersHandler.java:24) at io.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) at io.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by Zelldon**
Fixes wrong json template.

**Before**:
```json
{
		"testResult": "FAILED",
		"failureCount": 1,
		"failureMessages": [],
		"metaData": {
		}
}
```
**After**:

```json
{
	"testResult": "FAILED",
	"testReport": {
		"testResult": "FAILED",
		"failureCount": 1,
		"failureMessages": [],
		"metaData": {
		}
	}
}

```

Ideally we could define the template in one place where java and script clients can take it from.

closes #117

### CODE REVIEW

File: core/chaos-workers/handleJobTest.sh [hunk 1]
```diff
@@ -79,7 +79,7 @@ failFunction() {
 @test "run experiment with failing runner and values in array - return FAILED" {
   # given
   array=(1 2)
-  expected="$(jq -n '{testResult: "FAILED", failureMessages: ["1 failed"], failureCount: 1, metaData: {}}')"
+  expected="$(jq -n '{testResult: "FAILED", testReport: {testResult: "FAILED", failureMessages: ["1 failed"], failureCount: 1, metaData: {}}}')"
```
Comment (pihme) [inline core/chaos-workers/handleJobTest.sh:82]: This line and other lines:

I am not aware we have/need a top level `testResult` field. To the best of my recollection the after should be:
```
{
	"testReport": {
		"testResult": "FAILED",
		"failureCount": 1,
		"failureMessages": [],
		"metaData": {
		}
	}
}
```

**Review by pihme — CHANGES_REQUESTED** [review]
Please check where we need a top level `testResult` field.

File: core/chaos-workers/handleJobTest.sh (hunk 1 above)
Comment (Zelldon) [reply core/chaos-workers/handleJobTest.sh:82]: Currently we need because otherwise the xor gateway will not work

Comment (Zelldon) [reply core/chaos-workers/handleJobTest.sh:82]: Of course we can change that, but then lets do it in a separate issue

Comment (pihme) [reply core/chaos-workers/handleJobTest.sh:82]: So strange. I was under the impression that one of the output bindings takes out the testResult and puts it top level.

**Review by pihme — APPROVED** [review]
